// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewRecord struct {
	Num           string `json:"num"`
	Names         string `json:"names"`
	SumOfAllForks string `json:"sumOfAllForks"`
}
